//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniprojrect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjectIngredient")]
    public partial class ProjectIngredient
    {
        [Key]
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ProjectCategory ProjectCategory { get; set; }
    }
}
