
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Miniprojrect.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProjectUser()
    {

        this.ProjectOrders = new HashSet<ProjectOrder>();

    }


    public int UserId { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public string Addr { get; set; }

    public string PhoneNumber { get; set; }

    public string City { get; set; }

    public string Email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProjectOrder> ProjectOrders { get; set; }

}

}
